NewsWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('donate/', include('donate.urls'))
]

donate/urls.py
from django.urls import path, re_path
from . import views

app_name = 'donate'

urlpatterns = [
    path('', views.index, name='index'),

    # donate/id/
    #re_path(r'^(?P<donation_id>[0-9]+)/$', views.detail, name='detail'),

    path('MakeDonation/', views.detail, name='detail'),
]

donate/models.py
from django.db import models

# Create your models here.

class DonationLinks(models.Model):
    link_name = models.CharField(max_length=500)
    link = models.URLField(max_length=1000)
    link_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.link_name + "- " + self.link

donate/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import DonationLinks
# Create your views here.

def index(request):

    return render(request, 'donate/index.html') # arg is some text or html code

def detail(request):
    # try to go to a page and get donator name
    all_donation_links = DonationLinks.objects.all()
    context = {
        'all_donation_links': all_donation_links
    }
    return render(request, 'donate/detail.html', context)

donate/templates/donate/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Economica&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'donate/style.css' %}"/>
    <!-- Latest compiled and minified CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script async src="https://cse.google.com/cse.js?cx=010795098091594622132:sk6vx1kkg44"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Header-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'donate:index' %}">GetNews</a>
            </div>


            <!-- Items -->

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">


                    <li class="">
                        <a href="{% url 'donate:index' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'donate:detail' %}"> <!-- takes us to this url -->
                            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>&nbsp; Donate
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'donate:index' %}">
                            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp; News

                        </a>

                    </li>



                </ul>




                <ul class="nav navbar-nav navbar-right">

                    <div class="buscar-caja">


                        <div class="gcse-searchbox-only"></div>

                    </div>


                    <!--<form class="navbar-form navbar-right" action="/search.html">
                            <input type="text" class="form-control" name="q" value="">
                            <div class="gcse-searchbox-only"></div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>-->

                </ul>
            </div>
        </div>

    </nav>

    {% block body %}
    {% endblock %}



</body>
</html>

donate/templates/donate/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        table, th, td {
          border: 5px solid black;
          border-collapse: collapse;
        }
        th, td {
          padding: 15px;
          text-align: left;
        }
        table#t01 {
          width: 100%;
          background-color: #f1f1c1;
        }
    </style>

</head>
<body>

{% extends 'donate/base.html' %}

{% block body %}
    <table align="center">
        {% if all_donation_links %}
            <tr>
                <th>Name Of Organization</th>
                <th>Website</th>
            </tr>

            {% for donation_link in all_donation_links %}

                <tr>
                    <td>{{donation_link.link_name}}</td>
                    <td><a href="{{donation_link.link}}" target="_blank">Website</a></td>
                </tr>


            {% endfor %}

        {% else %}
            <h1>Sorry. Nothing to display at the moment. :(</h1>

        {% endif %}
    </table>
{% endblock %}


</body>
</html>

donate/templates/donate/index.html
<!DOCTYPE html>
<html lang="en">
<head>




</head>
<body>


    {% extends 'donate/base.html' %}

    {% block body %}


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="lion.jfif" alt="WHO">
          <div class="carousel-caption">
            <h3>WHO</h3>
            <!--<p>LA is always so much fun!</p>-->
          </div>
        </div>

        <div class="item">
          <img src="cdc.png" alt="CDC">
          <div class="carousel-caption">
            <h3>CDC</h3>
            <!--<p>Thank you, Chicago!</p>-->
          </div>
        </div>

        <div class="item">
          <img src="global.png" alt="Global">
          <div class="carousel-caption">
            <h3>Global Giving</h3>
            <!--<p>We love the Big Apple!</p>-->
          </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <!--<table align="center">
        {% if all_donation_links %}
            <tr>
                <th>Name Of Organization</th>
                <th>Website</th>
            </tr>

            {% for donation_link in all_donation_links %}

                <tr>
                    <td>{{donation_link.link_name}}</td>
                    <td><a href="{{donation_link.link}}">Website</a></td>
                </tr>


            {% endfor %}

        {% else %}
            <h1>Sorry. Nothing to display at the moment. :(</h1>

        {% endif %}
    </table>


    {% endblock %}

-->
    <!--<ul>
{% for donation_link in all_donation_links %}
    <li><a href="{{donation_link.link}}"target="_blank">{{donation_link.link_name}}</a></li>
{% endfor %}

</ul>-->

</body>
</html>